// types/transaction.ts
// This interface defines the structure for a transaction document (expense or income) in Firestore.

export type TransactionType = 'expense' | 'income';

export interface Transaction {
  id: string; // Firestore document ID (will be auto-generated by Firestore)
  userId: string; // ID of the user who owns this transaction
  name: string; // e.g., "Groceries", "Salary", "Dinner out"
  amount: number; // e.g., 50.75, 1500.00
  category: string; // e.g., "Food", "Transport", "Entertainment", "Utilities", "Salary", "Investment"
  date: string; // Date of the transaction, preferably in "YYYY-MM-DD" format
  currency: string; // e.g., "USD", "INR", "EUR"
  type: TransactionType; // 'expense' or 'income'
  notes?: string; // Optional: Any additional notes about the transaction
  createdAt: Date; // Timestamp of when the transaction was added to Firestore
}
